### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by 5tanly** [ammaraskar/pyCraft#112]

**Comment by 5tanly** [comment]
Ooops, forgot the description..

How do I install this so I can use it anywhere.

I tried:
python3.7 setup.py
pip install setup.py
pip install minecraft

Nothing works

**Comment by TheSnoozer** [comment]
There should be multiple ways...I somewhat would recommend to use a virtualenv. With that you could encapsulate different python installations. E.g. one where you test with the latest version of pycraft and one where you have the version you actively use (e.g. prod). This is not needed, but could pay off in certain conditions.
```
# initial virtualenv setup (needed only once)
virtualenv -p /usr/bin/python3.6 ~/pyenv/3.6

# active / use this specific environment (needed everytime you want to use python)
source ~/pyenv/3.6/bin/activate
```

Besides that if you have a local clone you should be able to use
```
python setup.py install
```
You would also need to install the requirements listed in the `requirements.txt` via
```
python -m pip install -r requirements.txt
```
You can also say `pip install -r requirements.txt`, but that might starts to create confusion, if you have multiple different python installations (python 2.7, 3.5, 3.6, ...). Specifying what python and what pip you use, would solve that (again personal recommendation, not required).

You could also install the requirements via a vcs url
```
python -m pip install git+https://github.com/ammaraskar/pyCraft@master#egg=minecraft
python -m pip install https://github.com/ammaraskar/pyCraft/archive/master.zip
```

instead of master you could also use a fixed commit e.g. (`python -m pip install git+https://github.com/ammaraskar/pyCraft@316ea4d63d6be5c59fe4b121db920b117130c6e9#egg=minecraft`)

but for that the requirements / dependencies are not automatically installed. If your dependencies grow, it might be worth creating your own dependencies.txt.
e.g.
```
cryptography>=1.5
requests
future
git+https://github.com/ammaraskar/pyCraft@master
```

As far as I can remember the setup.py could also specify dependencies (e.g. https://caremad.io/posts/2013/07/setup-vs-requirement/), but that is not the case for this library (actually not sure why).

Hope this helps.
