### ISSUE TITLE
Block placement code

### ISSUE THREAD

**Issue by RasphostUser** [ammaraskar/pyCraft#129]
Can anyone give working code of block placement? Because i don't understand how to use that

**Comment by joodicator** [comment]
Here is an example of a simple Minecraft bot that uses the `PlayerBlockPlacementPacket`. To run it:

1. Start a server (this was tested with version 1.14.2, but earlier or later versions will probably also work) with the following options in `server.properties` (before the first run of the server, so the world is generated correctly as flat):
```
level-type=flat
gamemode=creative
online-mode=false
spawn-monsters=false
spawn-npcs=false
spawn-animals=false
generate-structures=false
```
2. Join the server using **the bot's username** and put a block (which is placeable on top of grass - for example, cake) in the first inventory slot, then leave the server.
3. Join the server **using a different username**, to observe the bot.
4. Install pyCraft using `python setup.py install` or equivalent on the local machine.
5. Run [this script](https://gist.github.com/joodicator/e2066ba7337ec1826807426dcd236fc8) using Python 3, **replacing `CakeBot` with the bot's username**.

You should see the bot walking backwards, laying down a line of blocks in front of it, like so:
![Screenshot of the bot in action](https://i.imgur.com/seIv7JX.png)

I'm afraid that I do not have any examples at hand which are less contrived than this, because I have never used this functionality for an actual application. Perhaps someone else has a better example. :cake:
