### ISSUE TITLE
Add a way to make connection.connect() blocking

### ISSUE THREAD

**Issue by FTC55** [ammaraskar/pyCraft#131]
For my implementation I need a way to disconnect as soon as connection is established, just to determine wether the username is whitelisted or not on a server. However being that connection.connect() is apparently non blocking I can't have a connection.disconnect() call right after that or it won't even attempt to connect at all.

**Comment by joodicator** [comment]
It is not clear what you mean by "established" in this case, since a Minecraft connection goes through several initial stages before the user joins the game. I do not think that you want to only establish a TCP connection, though, since the authentication token (or username) will not have been sent to the server at this point, so it would only be useful for checking for an IP ban (and you don't need pyCraft for that).

If you're trying to find out whether the username is whitelisted, I think you'll want to wait until you receive either `clientbound.login.DisconnectPacket` or `clientbound.login.LoginSuccessPacket`. I believe what you are attempting is similar or identical to issue #128, in which more has been said about this.

**Comment by FTC55** [comment]
My issue is that i have to run connect() in a for loop to check for many servers one after the other, and what  ends up happening is that even if i have packet handlers that allow me to disconnect as soon as possible, what ends up happening is multiple connection attempts are made at once while the previous isn't yet completed and of course that is not possible with a single account. What i can do is set a timer to delay each connection but of course that's not optimal and it's only based on a guess of how much time the connection will take and it is prone to failure.

**Comment by joodicator** [comment]
@FTC55 In that case, I suggest using a condition variable to pause your main loop until each connection attempt has finished, like this:
```py
from threading import Condition

from minecraft.authentication import AuthenticationToken
from minecraft.networking.connection import Connection
from minecraft.networking.packets import clientbound
from minecraft.exceptions import LoginDisconnect

ADDRESSES = [...]

auth_token = AuthenticationToken()
auth_token.authenticate(...)

for address in ADDRESSES:
    conn = Connection(address=address, auth_token=auth_token)
    finished = Condition()

    @conn.listener(clientbound.login.LoginSuccessPacket)
    def on_login_success(packet):
        conn.disconnect()
        with finished:
            finished.can_login = True
            finished.notify()

    @conn.exception_handler(LoginDisconnect)
    def on_login_disconnect(exc, exc_info):
        with finished:
            finished.can_login = False
            finished.notify()

    with finished:
        conn.connect()
        finished.wait()
        print('%s: can_login=%r' % (address, finished.can_login))
```

I am not convinced that it is necessary to add a blocking version of `Connection.connect` to the library, since this seems like a fairly specialised use case.
