### ISSUE TITLE
Doesnt work with 1.10?

### ISSUE THREAD

**Issue by mdsitton** [ammaraskar/pyCraft#49]
It doesnt seem to currently support 1.10, it would certainly be nice if it did :)

**Comment by akselm** [comment]
I got a bot to join 1.10 using a dev build of the plugin ProtocolSupport, however the bots branch is still outdated :(

**Comment by ammaraskar** [comment]
Hi, I'm sorry but I really don't have time to maintain this project anymore. There's a bunch of other projects here that might help you out 

* http://wiki.vg/Library_List
* http://wiki.vg/Client_List

**Comment by joodicator** [comment]
This has been fixed in a753184ca24c8167743628c9106dc9207a6d7cc8.

Since I've been given push access to this repository, I'm going to continue keeping it up to date with Minecraft releases. However, I don't plan to implement any features beyond those needed for a chatbot. Therefore, if you're planning to start a new project, I would repeat @ammaraskar's suggestion of using a different library.

In any case, pull requests are still welcome.

**Comment by ammaraskar** [comment]
Thank you very much for your work @joodicator
