### ISSUE TITLE
High memory usage on server after ~12 hours

### ISSUE THREAD

**Issue by kyriog** [ammaraskar/pyCraft#70]
## Description

After ~ 12 hours with a pycraft account connected to a server (1.12.1), memory usage on server is way more higher than official client or Minecraft Console Client (more than 2×): on my Ubuntu server with 16GB RAM, using htop, official client consumes 2.2%, MCC (Minecraft Console Client) consumes 3.0% and Pycraft consumes 7.1%. This seems to happen too with 1.11.2 server.

I'm using the latest version `46e058d`, zip-downloaded from GitHub. But I was able to reproduce with an older version, before 1.12.

## Steps to reproduce

1. On a server, create a specific folder for Minecraft Server.
2. Download official server jar from Mojang: https://minecraft.net/fr-fr/download/server
3. Start a first time the server to generate eula.txt file.
4. Accept EULA.
5. Start again server, then run commands "difficulty 0" and "gamerule doMobSpawning false" to prevent mob generation (and random ram consumption).
6. Stop server.
7. (Optionnal) in server.properties, set online-mode to false to make tests easier.
8. Copy Minecraft Server folder twice: one for Pycraft client, one for MCC, one for official as reference.
9. In each directory, set a different listening port, and rename jar to readable name (for example, "minecraft_server.1.12.1_pycraft.jar")
10. Start each server
11. Connect at the same time one pycraft client, one MCC and one official client to its corresponding server.
12. Wait ~12 hours
13. Using any system tool, check memory usage for server: pycraft should use way more RAM than the others.

## Expected results

Pycraft server should use almost the same quantity of ram than the other clients.

**Comment by joodicator** [comment]
I will attempt to reproduce this when I have time to leave my machine with 2 server instances running. Presently, I cannot think what the cause could be, so I am curious to find out what it is.

**Comment by joodicator** [comment]
@kyriog [ORelio/Minecraft-Console-Client](/ORelio/Minecraft-Console-Client) seems to only support up to version 1.9, but you said you tried this with a 1.12.1 server. Is there some version of MCC that supports 1.12.1?

**Comment by kyriog** [comment]
@joodicator Yeah, exactly, I'm using the indev version of Minecraft Console Client. If needed, please note you can download the latest compiled build here: https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts (this link is available in their Indev readme)

**Comment by Warths** [comment]
I noticed that the RAM leak grows significantly faster when entity movements and block updates are involved (that's actually the reason that made @Kyriog do the experiment). 
Only 2 hours were needed to fill our 8Gb Ram limit with ~150 entity constantly moving and redstone updating frequently, resulting a crash of the server due to the TPS being too low. If that can help to fix this issue !

**Comment by joodicator** [comment]
I tried this on a 4GB Windows 7 machine for 12 hours with MCC and pyCraft, and although the memory usage increased slightly over 12 hours, and the server pyCraft was connected to was slightly ahead, there was hardly a difference:

![](http://i.imgur.com/0jxhfny.png)
(Blue: MCC; Red: pyCraft; vertical scale: 10^6 bytes)

I was not able to test it using Mojang's client, because that used too much memory and caused one of the servers to crash, but I might find a way to do that at another time.

**Comment by kyriog** [comment]
I reproduced my test, but this time I used the official Java runtime (1.8.0_131) instead of OpenJDK (same version).
I got some differences with the official client, but pycraft is still number 1 at memory usage.
Here's my htop result:
![putty_2017-08-18_15-06-00](https://user-images.githubusercontent.com/629831/29460145-1f503d82-8427-11e7-86ab-800ffea22987.png)

Maybe this issue only occurs on Linux? Or, as you have a "low ram" machine (4GB), Java limits the allowed memory?
I'll try tonight to reproduce the bug using my Windows computer as a server to see if I get the same results as you.

**Comment by joodicator** [comment]
I looked at the sequences of packets exchanged between the 1.12.1 server and, respectively, pyCraft, MCC and the vanilla client, and the one thing that MCC and vanilla have in common that pyCraft does not do is that they sent a `ClientSettingsPacket` upon joining the game, which includes an option for setting the view distance. The view distance set by MCC is `8`, which is also the default in vanilla. It could be that the lack of a view distance specification leaves it as the maximum, or causes some edge behaviour to be triggered in the server.

I have modified `start.py` on the `testing` branch, commit d1f61f2ea4bc3f0a40fc4d30075ee64157039e86, to send a `ClientSettingsPacket` that sets the view distance to just `1`. I wasn't sure what the effect of a view distance of `0` would be, but perhaps that could be experimented with as well. I would be interested to know if this reduces the memory usage of the server to a normal level, or even to a level below that with a vanilla client connected. I am unable to test it in the conditions of the reported memory leak, myself.

(While investigating this, I added a flag `-d` (`--dump-packets`) to `start.py`, which makes it print packets to `stderr` in a human-readable format, and should be useful for future debugging. I also wrote [this script](https://gist.github.com/joodicator/d75cf2c7e85aa9ac456d4cb520dfd119) that uses pyCraft to do the same thing for arbitrary Minecraft TCP streams saved from Wireshark, but I believe it has some bugs that appear when trying to parse longer packets)

**Comment by kyriog** [comment]
Here's the first results after 8h30 running:
![putty_2017-08-25_10-05-13](https://user-images.githubusercontent.com/629831/29705118-f9d385e0-897c-11e7-9a04-94f77f7e71a2.png)

I'll let the test running for today, I'll upload a new screen this evening.

**Comment by kyriog** [comment]
Here's the results, 19hr after start:
![firefox_2017-08-25_20-54-53](https://user-images.githubusercontent.com/629831/29728368-e3c9380c-89d7-11e7-849a-1d2e17e77646.png)

I'm not sure how to understand this result. Pycraft consumes this time less than official client (but still more than MCC), but all 3 consumes more than in the first test.

May you include this packet directly inside the library in another testing commit? I'll be able to test it on our real server, as my project doesn't use start.py but the library by itself (this project should be published on github soonish tho).

**Comment by joodicator** [comment]
@kyriog Commit d67285a on branch `issue70` will cause all `Connection`s to send this `ClientSettingsPacket`.

**Comment by kyriog** [comment]
I just updated our app to the latest commit of `issue70` branch (commit `593c98f`), and connected an account to one of our heavy-loaded entity zone.
I'll let @Warths posts the results in few hours.

**Comment by joodicator** [comment]
@kyriog 593c98f does not seem to be a pyCraft commit. Are you referring to a commit in your own project?

**Comment by kyriog** [comment]
@joodicator Woops, I mentioned the wrong commit as GitHub presents [compare views](https://github.com/ammaraskar/pyCraft/compare/issue70) in a reverse order than classic commits views.
But I downloaded the branch zip, so there's no impact on our tests.

**Comment by Warths** [comment]
I did 4 20 minutes test on our survival server, using all 4 programs, under extreme conditions, including : 

- Extreme entities motion
- intense block updates
- frequent light updates

Sidenote : We're using the Vanilla 1.12.1 version of the game provided by Mojang

Here's the result (Sorry for the hi-tech spreadsheet, i'm not a linux wizard)  : 
![d6f5d9290c45274c83a26b918cbbd639](https://user-images.githubusercontent.com/28197701/29751508-9fe75948-8b4e-11e7-8041-d5fe22b70904.png)

The difference between MCC and Vanilla may be due to the randomness of the test conditions. Same for the difference beetween pyCraft and pyCraft d67285a "PyCraft + Fix".

I'd like to try with a render distance of 10, just to see if it's influencing anything. i'll probably do it in few hours

**Comment by joodicator** [comment]
Interesting.

Just change this line, then: https://github.com/ammaraskar/pyCraft/blob/d67285a640c0f96efc285ddbb3b274448e26ff66/minecraft/networking/connection.py#L600

**Comment by kyriog** [comment]
We're launching a new test with a view_distance set to 10.

In order to be sure the problem doesn't come from my usage (which is a process running behind Gunicorn, as it's a webapp), I commented those two lines, which should prevent double ClientSettingsPacket:
https://github.com/ammaraskar/pyCraft/blob/issue70/start.py#L103-L104

**Comment by kyriog** [comment]
@joodicator I've noticed there's a nodejs implementation of Minecraft Client: https://github.com/PrismarineJS/node-minecraft-protocol
Could it be useful to you if we make the same tests using this library?

**Comment by joodicator** [comment]
@kyriog Yes, I think it may indeed be interesting to compare `node-minecraft-protocol` to `pyCraft` because, unlike MCC and the vanilla client, it aims to be a library rather than a client.

**Comment by Warths** [comment]
Added Node Minecraft Protocol results to the graph. 

![6768534725c8104ce9ecabfa7ea80da5](https://user-images.githubusercontent.com/28197701/29796302-a5145120-8c50-11e7-8d89-39b9c4977720.png)

We tried to run pyCraft with different settings for the render distance.

With render distance 10, we had one positive test, out of 2, and any other render distance between 13 and 8 gave negative results similar to the graph. I really don't know which conclusion it could mean.

**Comment by joodicator** [comment]
Quite interesting, indeed.

Can you tell me the details of how you ran the test using node-minecraft-protocol?

**Comment by kyriog** [comment]
@joodicator The test with Node Minecraft Protocol is ran using the same machine than the pycraft test on the graph, which is a Debian Jessie.
Player connected is the same on all clients, of course on the same block.

To run node-minecraft-protocol:
1. I installed nodejs 6 [using apt](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
2. Created an empty directory, then run `npm install minecraft-protocol` inside, as described in their readme ([installation part](https://github.com/PrismarineJS/node-minecraft-protocol#installation)).
3. Created a "client.js" file based on their [example](https://github.com/PrismarineJS/node-minecraft-protocol#echo-client-example) (I just changed IP and credentials).
4. Ran `node client.js`.

**Comment by Dinnerbone** [comment]
The vanilla Minecraft server ignores a clients view distance, so I don't see that likely being the cause. The packet is there for server modders to optimise if they felt brave enough, but we certainly didn't because it's very abusable.

**Comment by Warths** [comment]
@Dinnerbone i did an experiment to show why i thought it could be that. It's not render distance but something affect the server's behaviour.

I tried to load ungenerated portions of the map using different client and settings:

- No client - To generate spawn chunks
- Official Client - Render distance 16
- Minecraft Console client - Render distance 8
- pyCraft - Render distance 1
- Official Client - Render distance 2

I ran /tp ~ ~ ~200 few times on each client

And then i loaded the result with MCedit : 
![render_distance_experiment](https://user-images.githubusercontent.com/28197701/29817375-0aed5ad4-8cb8-11e7-96a8-358e03f1a7fc.png)

Intended behaviour : a 21x21 grid of chunks is loaded, generated and populated around the player everytime his character is moved

Actual behaviour : Only one chunk is loaded and generated for console clients. It's not populated as it does not fill the required conditions.

**Comment by Dinnerbone** [comment]
Okay, but isn't that because you're not acknowledging the teleport on your client? Does this actually have an impact on performance?

**Comment by joodicator** [comment]
pyCraft does automatically send teleport confirm packets when requested by the server (but since the vanilla client does this too, I didn't imagine it could be the cause of this issue).

**Comment by TheSnoozer** [comment]
just as an idea:
would be interesting to know if this issue also occurs on modded servers like spigot.
if so one might get more internal view with plugins like https://www.spigotmc.org/resources/lagmonitor.21348/
not sure if it actually would bring up the root cause but would be worth a try

**Comment by Warths** [comment]
I have no clue if it's because of that. It does not seem to affect server performances, but I just used that to demonstrate that the server behaviour is different, and it could cause the issue. But Joo said that it does send the packet and i assume Console Client also does. I'll try the same test with Node Minecraft Protocol as soon as i can. 

@TheSnoozer It's actually a good idea. I'll try to keep the same test conditions, but the lag does not occur if the ram is not saturated, so i dont know if lagmonitor could help us. I'll try though

**Comment by roblabla** [comment]
Worth noting that Node-Minecraft-Protocol(NMP) does not do a couple of things in the name of performance. Most notably, it will avoid decoding map packets, or storing them. It might be more interesting to benchmark mineflayer (a minecraft bot/client library, written on top of NMP), which does *a lot more*, among other things it also stores the chunk map.

**Comment by Pokechu22** [comment]
I did a quick test.  MCC allows enabling terrain and movement logic, but normally it's disabled for performance (if you're just chatting you don't need to handle the world).

Here's the teleporting from MCC with terrain and movement.  (With pycraft, the result is very similar)

![mccnoterrain](https://user-images.githubusercontent.com/8334194/29831398-e53b3bda-8c99-11e7-9f2a-dffbe7d79938.PNG)

And here's MCC once I enabled terrain and movement and restarted the client:

![mccwithterrain](https://user-images.githubusercontent.com/8334194/29831397-e50ee382-8c99-11e7-8e6d-2195213af5eb.PNG)

It's worth noting that MCC [does send the teleport confirm packet](https://github.com/ORelio/Minecraft-Console-Client/blob/fd2e3d5797615cd4707ac2db036b93ebb508f2b8/MinecraftClient/Protocol/Handlers/Protocol18.cs#L463-L468), but [only when terrain and movements are enabled](https://github.com/ORelio/Minecraft-Console-Client/blob/fd2e3d5797615cd4707ac2db036b93ebb508f2b8/MinecraftClient/Protocol/Handlers/Protocol18.cs#L445).

**Comment by Warths** [comment]
Just tried pyCraft with Bukkit and spigot.
![a75ce460875f2bc9febeb80d65f42fe0](https://user-images.githubusercontent.com/28197701/29833846-063cb54a-8ced-11e7-87a1-8d751dde3006.png)

![b3db21798c0b4da61cade1b3755a5761](https://user-images.githubusercontent.com/28197701/29833841-03cbda20-8ced-11e7-8e35-f328d8c24611.png)


While it's still causing a RAM leak on bukkit, it does not seem to be the case on Spigot, and i kept running pyCraft for over an hour

**Comment by Pokechu22** [comment]
I tweaked MCC to always confirm teleports even when terrain and movements is disabled; it still doesn't generate chunks beyond the one the player is in (just FYI).  So it's probably actual motion logic that matters, and that's probably not directly related to memory use.  Probably.

**Comment by Warths** [comment]
It's fine, my hypothesis was already confirmed wrong since MCC does not cause any ram issue but pyCraft does, and their behaviour with terrain and movements is the same

**Comment by TheSnoozer** [comment]
@Warths thats interesting to see. The results on bukkit server indicate that the problem seems to be still there but doesn't have the same impact as on a vanilla server.
What also might help is to create a thread dump with java visual VM. The thread dump would allow you to see what the java implementation does (please make at least 5 thread dumps with a ~5-10 sec wait in between). Not sure if this would help since minecraft is obfuscated.

note: you don't need to install anything on top visual vm should be shipped with java (not sure if it is only in the jdk)

**Comment by kyriog** [comment]
@TheSnoozer fyi, this issue can be reproduced using any world. Look at my firsts tests, I used a completly new world, issue still happen but it needs way more time to see a real difference.

**Comment by TheSnoozer** [comment]
@kyriog I saw that, but I'm not patient :P Why should I wait 24h for a possible issue to appear if there is "extreme test" with entities motion, intense block updates and frequent light update that gets me the issue reproduced within ~20 mins

**Comment by Warths** [comment]
As i can't provide the map that i used, i can recreate the same condition in a map that we can use as a reference for everyone. I'll do it tomorrow ! Stay tuned :) !

**Comment by Pokechu22** [comment]
Oh yea, if you do so - can you collect a heap dump with jvisualvm for both (Monitor tab, then right-click it in the sidebar and save as)?  That'd dump everything in memory, which'd be more useful for identifying what's using most of the memory.  (They'll be large files - that might make sharing them hard, but if you can get them it'd be a huge benefit).  Yes, obfuscation may be a bit of a problem, but MCP mappings do exist (and mojang can remap based off of their actual mappings), so it should still be very useful.

**Comment by kyriog** [comment]
@Pokechu22 I'm clearly not friendly with jvisualvm, do you mean [this software](https://visualvm.github.io/)? I found the monitor tab, but I didn't find where to right-click. Moreover as our server runs on a CLI Debian Server, I'll find how to connect to a remote JVM, any advice?

**Comment by Pokechu22** [comment]
Yea.

Creating a heap dump is just a button:

![createheapdump](https://user-images.githubusercontent.com/8334194/29849263-76e70394-8cda-11e7-92ac-828b919b1780.PNG)

You only right-click for saving it.

![saveheapdump](https://user-images.githubusercontent.com/8334194/29849264-76e904fa-8cda-11e7-88d5-ed9022756cee.png)

I'm not entirely sure how you use it remotely; give me a sec and I'll figure it out.

**Comment by kyriog** [comment]
@pokechu22 I just find out how to create a heap map directly from the server using jmap. We'll provide you dumps tomorrow.

**Comment by TheSnoozer** [comment]
A remote dump can be achieved by running the application with the following:
``
java -Dcom.sun.management.jmxremote.authenticate=false 
-Dcom.sun.management.jmxremote.ssl=false 
-Dcom.sun.management.jmxremote.port=3333 
``
on remote you would then specify `ip:3333``or whatever port you have used for `-Dcom.sun.management.jmxremote.port`

**Comment by TheSnoozer** [comment]
Not sure but I might have managed to reproduce this with
```
$ java -Xmx1024M -Xms1024M -jar minecraft_server.1.12.jar nogui
[02:20:28] [Server thread/INFO]: Starting minecraft server version 1.12
```
```
java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```
![selection_2017-08-30_03-17-42](https://user-images.githubusercontent.com/6849390/29851041-20d9fa62-8d32-11e7-9cc2-a2c584a16209.png)

```
[03:07:17] [Server thread/ERROR]: Encountered an unexpected exception
f: Ticking entity
	at net.minecraft.server.MinecraftServer.D(SourceFile:636) ~[minecraft_server.1.12.jar:?]
	at nx.D(SourceFile:343) ~[minecraft_server.1.12.jar:?]
	at net.minecraft.server.MinecraftServer.C(SourceFile:560) ~[minecraft_server.1.12.jar:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [minecraft_server.1.12.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.LinkedHashMap$LinkedKeySet.iterator(LinkedHashMap.java:543) ~[?:1.8.0_144]
	at java.util.HashSet.iterator(HashSet.java:172) ~[?:1.8.0_144]
	at xd.a(SourceFile:81) ~[minecraft_server.1.12.jar:?]
	at vo.cA(SourceFile:637) ~[minecraft_server.1.12.jar:?]
	at vn.n(SourceFile:1887) ~[minecraft_server.1.12.jar:?]
	at vo.n(SourceFile:501) ~[minecraft_server.1.12.jar:?]
	at vb.n(SourceFile:144) ~[minecraft_server.1.12.jar:?]
	at vn.B_(SourceFile:1742) ~[minecraft_server.1.12.jar:?]
	at vo.B_(SourceFile:281) ~[minecraft_server.1.12.jar:?]
	at ams.a(SourceFile:1523) ~[minecraft_server.1.12.jar:?]
	at om.a(SourceFile:714) ~[minecraft_server.1.12.jar:?]
	at ams.h(SourceFile:1499) ~[minecraft_server.1.12.jar:?]
	at ams.k(SourceFile:1382) ~[minecraft_server.1.12.jar:?]
	at om.k(SourceFile:547) ~[minecraft_server.1.12.jar:?]
	at net.minecraft.server.MinecraftServer.D(SourceFile:632) ~[minecraft_server.1.12.jar:?]
	... 4 more
```

**Comment by Dinnerbone** [comment]
After some experimenting, I can confirm that there is indeed an issue on the vanilla server which can cause it to memory leak if a client behaves in a certain way.

I believe that there is a bug in this library that unintentionally triggers this behaviour after a certain point, which highlights the problem in the server.

I can't give any more details currently as we're going to treat this as a security issue as it can be exploitable, and therefore aim to release a 1.12.2 to fix it.

After 1.12.2 is out with the fix, this client will likely just disconnect after it hits this behaviour. I can share some more details on what I found then.

**Comment by kyriog** [comment]
@Dinnerbone fyi, I'm not 100% sure but I think we firstly saw this problem running 1.11.2 (still Vanilla server). So if you still support 1.11, a 1.11.3 may be required. Do you want that we confirm this point or do you manage it by yourself?
I don't know if the issue is also present on < 1.11 as we didn't use pycraft before.

**Comment by Dinnerbone** [comment]
We only support the latest release, so there won't be a 1.11.3 sorry.

**Comment by kyriog** [comment]
@joodicator any way to contact you in private to keep going on this issue while Mojang's fixing it in 1.12.2?

**Comment by sgdc3** [comment]
@Dinnerbone will the new version change the protocol version? It's a mess to update all my software on every minor release.

**Comment by Dinnerbone** [comment]
Every release is a new protocol version. Especially security releases.

**Comment by joodicator** [comment]
Interesting. I suppose we'll have to wait until the release to find out what the bug is and fix it in pyCraft.

**Comment by Warths** [comment]
If that's useful for you, i can provide you a test map and a memory dump before/after a test. Tell me if you need me to take some time to do that

**Comment by ammaraskar** [comment]
>After 1.12.2 is out with the fix, this client will likely just disconnect after it hits this behaviour. I can share some more details on what I found then.

@Dinnerbone can you share a little bit more on what was happening now that it's out?

**Comment by TheSnoozer** [comment]
This might even be related to the change in 1.12.2-pre1, -pre2:
http://wiki.vg/Protocol_History#1.12.2-pre1.2C_-pre2
but still +1 for some more insight

**Comment by Dinnerbone** [comment]
I believe that this library somehow enters a state where it's slowly churning through a packet backlog, not reading anything new from the connection but still writing to it. This causes the server to build up a big buffer of packets to send to the client waiting for it to read them.

**Comment by ammaraskar** [comment]
Interesting, because the library only writes a packet if it receives one, by default it never writes any packets by itself.

**Comment by Dinnerbone** [comment]
Is it possible that your writes are long blocking; taking a very long time to send stuff that your incoming queue builds up? (You only read 50 packets at a time, so the buffer can grow and grow if you're not fast enough)

**Comment by joodicator** [comment]
> Is it possible that your writes are long blocking; taking a very long time to send stuff that your incoming queue builds up? (You only read 50 packets at a time, so the buffer can grow and grow if you're not fast enough)
This sounds like it may be at the root of the problem. To see whether this is the case, I have modified the `Connection` class on branch `issue70` so that every 5 minutes it writes some relevant statistics to a JSON profile report file. For anybody able to reproduce this issue, I would be interested to see the corresponding profile report after it has been left long enough to accumulate some memory leakage. It would be particularly interesting to also see the results for a server that has a lot of activity, which supposedly increases the rate of leakage.

@kyriog
> @joodicator any way to contact you in private to keep going on this issue while Mojang's fixing it in 1.12.2?
Sorry: I did not see this message until just now. I don't think it will be necessary to contact me in private now that the nature of the issue is public, but please do so if you wish to.

**Comment by kyriog** [comment]
@joodicator We've run pycraft with profiler for ~2hr. Before starting the test, our server were using 3GB of RAM. At the end of the test, we were using 9GB.

Here's the results:
```json
{
    "reads": 7866594,
    "read_time": 211.67856995365582,
    "writes": 1596,
    "iterations": 157346,
    "write_time": 1.4820954732131213,
    "sleep_time": 7883.463666583877,
    "iter_reads": 49.99551307310005,
    "iter_writes": 0.01014325117893051,
    "iter_read_time": 0.0013453063309754034,
    "iter_write_time": 9.419340009997848e-06,
    "iter_sleep_time": 0.05010272689857942
}

It's not necessary anymore to get in touch in private now, as the issue is public and a fix is available.
```

**Comment by TheSnoozer** [comment]
with 1.12:
```
{
    "write_time": 2.0501981644774787,
    "sleep_time": 5482.1494507358875,
    "read_time": 513.9717971003847,
    "writes": 578,
    "iterations": 109151,
    "reads": 5350393,
    "iter_reads": 49.01826827056097,
    "iter_writes": 0.005295416441443505,
    "iter_read_time": 0.004708814368172391,
    "iter_write_time": 1.87831367965248e-05,
    "iter_sleep_time": 0.05022537082331713
}
```

**Comment by joodicator** [comment]
It appears that the client is reaching the limit of 50 packets read per 50ms during most iterations of the networking thread loop. @ammaraskar Do you know what the rationale was for the limit of 50 packets in particular? Should there be a limit at all?

**Comment by ammaraskar** [comment]
@joodicator the limit was just an arbitrary number I picked. The reason it exists is because if the server continually sends a stream of packets we won't have a chance to send back any replies. I think the network loop can likely be made to sleep less often and the limit raised safely.

**Comment by joodicator** [comment]
@ammaraskar Instead of raising the limit to another fixed value, which would risk being exceeded in some other use case, I propose allowing the networking thread to read/write as many packets as are immediately available while still interleaving reads and writes so that both activities can progress concurrently. I've implemented this in commit af559e1 by replacing the `sleep(0.05)` call with a `read_packet` call which may block for up to 0.05 seconds if there are no more packets to write: https://github.com/ammaraskar/pyCraft/blob/af559e181ae7c6df9cb8d71e5cd4aa57b8bbf2ff/minecraft/networking/connection.py#L401-L440.

@TheSnoozer and @kyriog: if my understanding of the problem is correct, commit af559e1 on `testing` should resolve this problem (although some details of the fix are still under discussion). I would be interested to know whether this is the case.

**Comment by ammaraskar** [comment]
@joodicator This sounds like a good strategy to me. Please check that it doesn't cause outgoing packets to wait too long before they can be written.

**Comment by TheSnoozer** [comment]
@joodicator I'm not 110% yet if the fix fully solved the issue but I can confirm so far that the memory consumption now seems somewhat more normal. Before that fix I was able to reproduce the issue within ~30mins and now could leave the client running for 3h and 20mins.

Some background
```
$ git rev-parse HEAD
af559e181ae7c6df9cb8d71e5cd4aa57b8bbf2ff
```

Consumption (%Y-%m-%d_%H-%M-%S):
``Virt: 4196M; RES 560M`` - server start (2017-10-10_17-19-14)
``Virt: 4560M; RES 644M`` - client join (2017-10-10_17-20-11)
``Virt: 4560M; RES 971M`` - client left (2017-10-10_20-44-14)

The memory consumption for RES is slowly growing but considering the client was running for 3h and 20mins the increase of 330M doesn't sound too bad (was way worse before).

The main reason why I'm still not 110% sure that the issue was fixed for all cases is that the server spit out the following log:
```
[17:19:51] [Server thread/INFO]: [USER] joined the game
[17:28:08] [Server thread/WARN]: Fetching addPacket for removed entity
[17:32:40] [Server thread/WARN]: Fetching addPacket for removed entity
[18:01:37] [Server thread/WARN]: Fetching addPacket for removed entity
[18:01:49] [Server thread/WARN]: Fetching addPacket for removed entity
[18:09:37] [Server thread/WARN]: Fetching addPacket for removed entity
[18:19:51] [Server thread/WARN]: Fetching addPacket for removed entity
[18:32:36] [Server thread/WARN]: Fetching addPacket for removed entity
[18:33:40] [Server thread/WARN]: Fetching addPacket for removed entity
[18:41:06] [Server thread/WARN]: Fetching addPacket for removed entity
[18:42:39] [Server thread/WARN]: Fetching addPacket for removed entity
[18:52:10] [Server thread/WARN]: Fetching addPacket for removed entity
[18:56:41] [Server thread/WARN]: Fetching addPacket for removed entity
[18:57:36] [Server thread/WARN]: Fetching addPacket for removed entity
[19:25:36] [Server thread/WARN]: Fetching addPacket for removed entity
[19:42:09] [Server thread/WARN]: Fetching addPacket for removed entity
[19:43:04] [Server thread/WARN]: Fetching addPacket for removed entity
[19:44:01] [Server thread/WARN]: Fetching addPacket for removed entity
[19:45:15] [Server thread/WARN]: Fetching addPacket for removed entity
[20:22:07] [Server thread/WARN]: Fetching addPacket for removed entity
[20:44:29] [Server thread/INFO]: [USER] lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
[20:44:29] [Server thread/INFO]: [USER] left the game
```

never saw this warning before and can't tell why and where it comes from.

If it would make sense I can also test with https://github.com/ORelio/Minecraft-Console-Client/ to see what memory impact this particular client has.

**Comment by Pokechu22** [comment]
That message happens when a dead entity (dead as in removed from the world) is supposed to be sent to a client.  It's... odd that you're seeing it.

Do try with MCC, both for memory and that warning.

**Comment by TheSnoozer** [comment]
Just wanted to check-in if there is anything that I just further on this issue?
Let me know if I should run longer tests (or anything else)..

**Comment by joodicator** [comment]
@kyriog @TheSnoozer Since it seems that that af559e1 fixes this issue, and I have not seen any reports to the contrary, I have merged the fix into `master` and will close this issue. However, feel free to leave comments if there are any other problems.

@ammaraskar
> This sounds like a good strategy to me. Please check that it doesn't cause outgoing packets to wait too long before they can be written.

It is possible with this change (and was possible before the change) for the outgoing packet queue to grow unbounded in length and eventually cause an OOM condition, but, if I am correct, only if:
1. The client is receiving so many packets from the server that it does not have enough CPU time to process both incoming and outgoing packets, **and**
2. The client is queueing more than 6 outgoing packets per incoming packet, on average.

In this case, it isn't possible for the client to keep up with both tasks, so one or both of them will inevitably fall behind. If the reading process falls behind, the vanilla server will (as of 1.12.2) eventually kick the client. If the writing process falls behind, the client might run out of memory. It would be nice if the library could handle this condition more gracefully, but, since I can't think of a particularly good way of dealing with it, and since it's unlikely to occur unless the library is being abused, I think I'll leave it as it is for now.
