### ISSUE TITLE
How to get client's health?

### ISSUE THREAD

**Issue by MatCorgi** [ammaraskar/pyCraft#75]
I'm really new to this.

**Comment by joodicator** [comment]
Listen for the **Update Health** packet, documented [here](http://wiki.vg/Protocol#Update_Health) on wiki.vg, and defined [here](https://github.com/ammaraskar/pyCraft/blob/e9f095de4266ca7a54c0ebe48561a9076019a7b1/minecraft/networking/packets/clientbound/play/__init__.py#L152) in pyCraft's source.

For example, the example program `start.py` can be modified by adding these lines before `connection.connect()`:
```py
    def update_health(health_packet):
        print('Health: %.2f' % health_packet.health)

    connection.register_packet_listener(
        update_health, clientbound.play.UpdateHealthPacket)
```
Since the event handler is run in a thread separate from the main thread, you will probably want to use a synchronisation mechanism like a condition variable if you want to make use of the health value in a larger program, as in the example in [this comment](https://github.com/ammaraskar/pyCraft/issues/62#issuecomment-312612789).

**Comment by joodicator** [comment]
I'm closing this issue as there have been no comments for 4 months, but if you have any further questions, feel free to post them here.
