### ISSUE TITLE
How to read packet map and get image in jpg

### ISSUE THREAD

**Issue by maxim19116** [ammaraskar/pyCraft#78]
How to make it so that if at the entrance there was a map in hand and read this picture and write it in jpg format

**Comment by joodicator** [comment]
To do this requires a bit of additional work to convert the map pixel colour IDs to standard colour values. I maintain a utility that does this (except it saves PNG files instead of JPEGs) using pyCraft and another library I maintain (which does most of the work) called mcmapimg. You can look at the source code of both to see how it can be done:
* https://github.com/joodicator/mcchat2/blob/master/plugins/mapimg/mcchat_mapimg.py
* https://github.com/joodicator/mcmapimg

**Comment by ammaraskar** [comment]
Please re-open this if you still need help.
