### ISSUE TITLE
No module named 'minecraft.networking.types'

### ISSUE THREAD

**Issue by Alpakaaa** [ammaraskar/pyCraft#97]
So after I try running start.py I get:

> Traceback (most recent call last):
  File "C:/Users/bocza/PycharmProjects/bot_minecraft_1.12/main.py", line 4, in <module>
    from minecraft.networking import connection
  File "C:\Users\bocza\AppData\Local\Programs\Python\Python36\lib\site-packages\minecraft\networking\connection.py", line 16, in <module>
    from .types import VarInt
ModuleNotFoundError: No module named 'minecraft.networking.types'

And I tried multiple solutions but none seems to work. I am running Windows 10 with Python 3.6.3.

**Comment by joodicator** [comment]
Whoops, this is a regression caused by 61598eba7559d73f80be194fde0bd89d8c3d2ef6 adding a new package without adding it to `setup.py`. My fault. This has been fixed in 745aa05.

We either need to automatically verify that `setup.py` is working correctly, or have it automatically populate the list of packages, or both.
